package com.johnlpage.datagen;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.List;

public class DataGen {

  public static void main(String[] args) throws IOException {

    String directoryPath;
    int numberOfJsonDocuments;
    String outputPath;

    if (args.length < 3) {
      System.out.println(
          " 1 Usage: java -jar DataGen.jar definitionDirectory count outputPath [batchSize]");
      System.exit(1);
    }
    directoryPath = args[0];
    numberOfJsonDocuments = Integer.parseInt(args[1]);
    outputPath = args[2];

    // Each top-level document generated by this tool can expand into a very large in-memory
    // object graph once you factor in nested arrays (e.g. photos, priceHistory, nearbyHomes,
    // homeValuation.comparables.comps...). Holding a huge batch of these fully-expanded
    // documents in memory at once (the old default was 50,000) can exhaust the JVM heap well
    // before you reach the total document count you asked for - the OutOfMemoryError happens
    // while building/writing a single batch, regardless of how large `count` is. Keeping the
    // batch size modest bounds peak memory usage independent of the total requested count.
    // Override with a 4th CLI argument if you have more headroom (and/or run with a larger
    // -Xmx) and want higher throughput.
    int batchSize = 2000;
    if (args.length >= 4) {
      batchSize = Integer.parseInt(args[3]);
    }

    DataGenProcessor processor = new DataGenProcessor(directoryPath);
    ObjectMapper objectMapper = new ObjectMapper();
    ObjectWriter objectWriter = objectMapper.writer();
    LocalDateTime startTime = LocalDateTime.now();
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(outputPath))) {
      for (int docs = 0; docs < numberOfJsonDocuments; docs += batchSize) {
        int docsInBatch = batchSize;
        if (docs + batchSize > numberOfJsonDocuments) {
          docsInBatch = numberOfJsonDocuments - docs;
        }

        List<ObjectNode> documents = processor.generateJsonDocuments(docsInBatch);

        for (ObjectNode document : documents) {
          writer.write(objectWriter.writeValueAsString(document));
          writer.newLine();
        }
        // Allow the batch (and all the nested ObjectNodes it contains) to be garbage collected
        // before the next batch is generated.
        documents = null;
        LocalDateTime now = LocalDateTime.now();
        Duration duration = Duration.between(startTime, now);

        long millis = duration.toMillis();
        if (millis > 1) {
          double predictedSeconds = (double) (numberOfJsonDocuments * millis) / (docs + batchSize);
          int remaining = (int) Math.floor((predictedSeconds - millis) / 1000);

          System.out.println(
              "Generated "
                  + (docs + docsInBatch)
                  + " of "
                  + numberOfJsonDocuments
                  + " documents in "
                  + duration.toSeconds()
                  + " s , estimating "
                  + remaining
                  + " seconds remaining");
        }
      }
    } catch (IOException e) {
      System.err.println("Error: " + e.getMessage());
    }
  }
}
